### ISSUE TITLE
Deriving some common traits + defmt feature and `no_std` support

### ISSUE THREAD

**Issue by elpiel** [mariano-f-r/parse_rc_ibus#2]
- [x] In addition to the current Debug derive of `IbusPacket` and `ParsingError` it would be nice to have Clone/Copy and `defmt::Format` (enabled with a features as an optional dep.) to be used in `no_std` environment.

- [x] To support `no_std` we can use `core::error::Error` (which is stable since `1.81`) so either a MSRV should be added or `std::error::Error` impl should be enabled only with a feature, e.g. `std` feature.
- [x] core::fmt::Display can be used instead of the std::fmt::Display to support `no_std`

**Comment by mariano-f-r** [comment]
I will definitely try to migrate the traits provided by `std` to `core`, as that is an easy fix. As to why I never did it sooner, I built this for a drone with a flight controller running in a Raspberry Pi 4's userland.

As to the dependencies, I've never actually written a crate with feature flags, although I imagine it is not difficult.

I will begin working on this once my studies become less difficult.

**Comment by elpiel** [comment]
That's great! Good luck with your studies.
I can also open a PR, however, it might be a good opportunity for you to exercise adding features to crates.

Do let me know if you need some assistance.
PS: You can also check e.g. our nmea crate as it adds conditions derives to structures based on feature flags: https://github.com/AeroRust/nmea/

**Comment by mariano-f-r** [comment]
Done.

Core traits added with 4e985e595ce62b808fa86f8ac74a1c762e7ca642
Copy and clone were added with 09bbdc4a7560a3d69bd2bdf25308cc7c061af958
and defmt support was added with 3aafa0b4ec893f4c2b8bdaee0e0125b625cc0b7d

Unfortunately due to not being able to enable features for tests (which is currently being discussed [here](https://github.com/rust-lang/cargo/issues/2911)), I could not verify the functionality of the defmt feature working. Given how simple the derive was, I imagine it works fine.

**Comment by elpiel** [comment]
Yaay! Btw for MSRV you can add "rust-version" to Cargo.toml
